// This file is auto generated by script
// Date: 18/12/2021 01:01:19

#include <string>
#include <array>

#include "rapidjson/document.h"
#include "rapidjson/writer.h"
#include "rapidjson/stringbuffer.h"

namespace json_autogenerated_classes {

  struct Units {
    struct Archer {
      int health = 100;
      std::string dragonbones = "archer";
      struct Weapons {
        struct Bow {
          std::string description = "fire arrows, wtf?";
          std::string type = "range";
          float range = 50.0f;
          float cooldown = 0.5f;
          struct Projectile {
            std::string type = "arrow";
            std::array<float, 2> velocity = { 300.0f, 0.0f };
            float damage = 5.0f;
            float lifetime = 3.0f;
          } projectile;
        } bow;
      } weapons;
    } archer;
    struct BanditBoss {
      int health = 500;
      std::string dragonbones = "boss";
      float jumpHeight = 80.0f;
      float defaultSpeed = 190.0f;
      float enhancedSpeed = 280.0f;
      struct Weapons {
        struct Dash {
          std::string description = "extremly fast move forward";
          float cooldown = 13.0f;
          std::array<float, 2> velocity = { 600.0f, 0.0f };
        } dash;
        struct Firebook {
          std::string description = "throws fire from his chains into the enemy";
          std::string type = "range";
          float range = 60.0f;
          float cooldown = 2.0f;
          struct Projectile {
            std::string type = "fireball";
            std::array<float, 2> velocity = { 400.0f, 0.0f };
            float damage = 15.0f;
            float lifetime = 5.0f;
          } projectile;
        } firebook;
        struct Firecloud {
          std::string description = "summon firecloud which will attack with fireballs from the air";
          float range = 130.0f;
          float cooldown = 5.0f;
          std::array<float, 2> impulse = { 0.0f, 190.0f };
        } firecloud;
        struct ChainSweep {
          std::string description = "jump and sweep his chains over the enemy once";
          std::string type = "range";
          float range = 100.0f;
          float cooldown = 8.0f;
          struct Projectile {
            std::string type = "chain";
            float damage = 30.0f;
            float lifetime = 0.15f;
          } projectile;
        } chainSweep;
        struct ChainSwing {
          std::string description = "stops and swing chains trice";
          std::string type = "range";
          float range = 140.0f;
          float cooldown = 2.0f;
          struct Projectile {
            std::string type = "chain";
            float damage = 15.0f;
            float lifetime = 0.15f;
          } projectile;
        } chainSwing;
      } weapons;
    } banditBoss;
    struct BoulderPusher {
      int health = 100;
      std::string dragonbones = "old_man";
      struct Weapons {
        struct Legs {
          std::string description = "throws a boulder from the above";
          std::string type = "melee";
          float range = 18.0f;
          float cooldown = 1.5f;
          struct Projectile {
            std::string type = "boulder";
            std::array<float, 2> impulse = { 200.0f, 0.0f };
            std::array<float, 2> angular = { 10.0f, 0.0f };
            float damage = 5.0f;
            float lifetime = 5.0f;
          } projectile;
        } legs;
      } weapons;
    } boulderPusher;
    struct Cannon {
      int health = 250;
      std::string dragonbones = "cannon";
      struct Weapons {
        struct Cannon {
          std::string description = "fire stakes";
          std::string type = "range";
          float range = 50.0f;
          float cooldown = 0.3f;
          struct Projectile {
            std::string type = "stake";
            std::array<float, 2> velocity = { 450.0f, 0.0f };
            float damage = 15.0f;
            float lifetime = 5.0f;
          } projectile;
        } cannon;
      } weapons;
    } cannon;
    struct Firecloud {
      int health = 10000;
      std::string dragonbones = "cloud";
      float shellRefillCooldown = 0.7f;
      int shellRefillCount = 4;
      float lifetime = 4.0f;
      float maxSpeed = 100.0f;
      struct Weapons {
        struct Fireball {
          std::string description = "throws fireballs from the cloud";
          std::string type = "range";
          float range = 115.0f;
          float cooldown = 0.1f;
          struct Projectile {
            std::string type = "fireball";
            std::array<float, 2> velocity = { 300.0f, 600.0f };
            float damage = 15.0f;
            float lifetime = 3.0f;
          } projectile;
        } fireball;
      } weapons;
    } firecloud;
    struct Player {
      int health = 100;
      std::string dragonbones = "mc";
      float maxSpeed = 200.0f;
      struct Weapons {
        struct Sword {
          std::string description = "simple attack with sword: upper, middle, lower";
          std::string type = "melee";
          float range = 80.0f;
          float cooldown = 0.0f;
          float damage = 25.0f;
        } sword;
        struct Spell {
          std::string description = "throws fireball";
          std::string type = "range";
          float range = 110.0f;
          float cooldown = 0.0f;
          struct Projectile {
            std::string type = "fireball";
            std::array<float, 2> velocity = { 450.0f, 0.0f };
            float damage = 25.0f;
            float lifetime = 4.0f;
          } projectile;
        } spell;
        struct Special {
          std::string description = "sword attack produces and throw an arc of fire";
          std::string type = "range";
          float range = 180.0f;
          float cooldown = 0.0f;
          struct Projectile {
            std::string type = "fireslash";
            std::array<float, 2> velocity = { 550.0f, 0.0f };
            float damage = 55.0f;
            float lifetime = 4.0f;
          } projectile;
        } special;
        struct Dash {
          std::string description = "extremly fast move forward";
          float cooldown = 0.7f;
          std::array<float, 2> velocity = { 600.0f, 0.0f };
        } dash;
      } weapons;
    } player;
    struct Slime {
      int health = 100;
      std::string dragonbones = "slime";
      float maxSpeed = 80.0f;
      struct Weapons {
        struct Spell {
          std::string description = "throws waterball";
          std::string type = "range";
          float range = 120.0f;
          float cooldown = 0.5f;
          struct Projectile {
            std::string type = "waterball";
            std::array<float, 2> velocity = { 450.0f, 0.0f };
            float damage = 25.0f;
            float lifetime = 4.0f;
          } projectile;
        } spell;
      } weapons;
    } slime;
    struct Spearman {
      int health = 100;
      std::string dragonbones = "spear_man";
      float maxSpeed = 75.0f;
      struct Weapons {
        struct Spear {
          std::string description = "attack with spear";
          std::string type = "melee";
          float range = 50.0f;
          float cooldown = 1.4f;
          float damage = 10.0f;
        } spear;
      } weapons;
    } spearman;
    struct Spider {
      int health = 100;
      std::string dragonbones = "spider";
      float linewidth = 25.0f;
      float idleSpeed = 60.0f;
      float alertSpeed = 100.0f;
    } spider;
    struct Stalactite {
      int health = 100;
      std::string dragonbones = "stalactite";
      struct Weapons {
        struct Stalactite {
          std::string description = "part of the stalactite breaks off and falls on enemies";
          std::string type = "range";
          float cooldown = 0.3f;
          float damage = 30.0f;
          std::array<float, 2> velocity = { 0.0f, 400.0f };
        } stalactite;
      } weapons;
    } stalactite;
    struct AxWarrior {
      int health = 100;
      std::string dragonbones = "warrior";
      float maxSpeed = 80.0f;
      struct Weapons {
        struct Axe {
          std::string description = "axe attack";
          std::string type = "melee";
          float range = 30.0f;
          float cooldown = 0.5f;
          float damage = 15.0f;
        } axe;
      } weapons;
    } axWarrior;
    struct Wasp {
      int health = 100;
      std::string dragonbones = "wasp";
      float idleSpeed = 35.0f;
      float alertSpeed = 70.0f;
      struct Weapons {
        struct Sting {
          std::string description = "sting enemy";
          std::string type = "melee";
          float range = 15.0f;
          float cooldown = 0.6f;
          float damage = 10.0f;
        } sting;
      } weapons;
    } wasp;
    struct Wolf {
      int health = 100;
      std::string dragonbones = "wolf";
      float idleSpeed = 100.0f;
      float alertSpeed = 200.0f;
      struct Weapons {
        struct Maw {
          std::string description = "bite an enemy";
          std::string type = "melee";
          float range = 10.0f;
          float cooldown = 0.4f;
          float damage = 20.0f;
        } maw;
      } weapons;
    } wolf;
  };

} // namespace json_autogenerated_classes
